### ISSUE TITLE
Spec projects - verify names specifications

### ISSUE THREAD

**Issue by jr0cket** [practicalli/clojure-practicalli-content#180]
*** TODO Check requires meet team specifications
    - [ ] Ensure single character aliases are not used
    - [ ] Add alias exception for cognitect spec and datomic
    - [ ] Ensure names of existing clojure.core functions are not used
    - [ ] Add aliases for common libraries (eg. integrant can be :ig :integrant :component :system :lifecycle)
